android.nonTransitiveRClass=true
android.uniquePackageNames=false
android.useAndroidX=true
appVersionCode=2026083110
appVersionName=2.0.3

kotlin.apple.xcodeCompatibility.nowarn=true
kotlin.code.style=official
kotlin.mpp.enableCInteropCommonization=true
kotlin.mpp.enableCInteropCommonization.nowarn=true

kotlin.native.cache.kind=none
kotlin.native.disableCompilerDaemon=true

org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.daemon=true
org.gradle.isolated-projects=false
org.gradle.jvmargs=-Xmx10g -Dkotlin.daemon.jvm.options\="-Xmx2g" -XX\:MaxMetaspaceSize\=1g -Dfile.encoding\=UTF-8
ksp.project.isolation.enabled=false

org.gradle.vfs.watch=false
org.gradle.warning.mode=none
org.gradle.workers.max=4
org.gradle.parallel=true
org.gradle.tooling.parallel=true
