# Kotlin
kotlin.code.style=official
# Native
kotlin.apple.xcodeCompatibility.nowarn=true
# Gradle
org.gradle.jvmargs=-Xmx8g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -XX:+UseParallelGC -XX:MaxMetaspaceSize=1g
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.workers.max=18
org.gradle.configuration-cache=true
org.gradle.warning.mode=none
org.gradle.vfs.watch=false
# Android
android.nonTransitiveRClass=true
android.useAndroidX=true
android.uniquePackageNames=false
# Cinterop commonization
kotlin.mpp.enableCInteropCommonization=true
kotlin.mpp.enableCInteropCommonization.nowarn=true

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
# Enables Gradle Isolated Projects for better configuration performance.
org.gradle.isolated-projects=true
ksp.project.isolation.enabled=true