# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iosApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iosApp
  pod 'core_native', :path => '../shared/core_native'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|

      # Disable signing for all synthetic pods KT-54314
      config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
      config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
      config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"

      deployment_target_split = config.build_settings['IPHONEOS_DEPLOYMENT_TARGET']&.split('.')
      deployment_target_major = deployment_target_split&.first&.to_i
      deployment_target_minor = deployment_target_split&.second&.to_i

      if deployment_target_major && deployment_target_minor then
        if deployment_target_major < 12 || (deployment_target_major == 12 && deployment_target_minor < 0) then
            version = "#{12}.#{0}"
            puts "Deployment target for #{target} #{config} has been raised to #{version}. See KT-57741 for more details"
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = version
        end
      end
    end
  end
end