package com.xiaoyv.emoji

/**
 * Class: [BgmEmoji]
 *
 * @author why
 * @since 11/27/23
 */
object BgmEmoji {

    val normalEmoji by lazy {
        linkedMapOf(
            "(=A=)" to R.drawable.normal_1,
            "(=w=)" to R.drawable.normal_2,
            "(-w=)" to R.drawable.normal_3,
            "(S_S)" to R.drawable.normal_4,
            "(=v=)" to R.drawable.normal_5,
            "(@_@)" to R.drawable.normal_6,
            "(=W=)" to R.drawable.normal_7,
            "(TAT)" to R.drawable.normal_8,
            "(T_T)" to R.drawable.normal_9,
            "(='=)" to R.drawable.normal_10,
            "(=3=)" to R.drawable.normal_11,
            "(= =')" to R.drawable.normal_12,
            "(=///=)" to R.drawable.normal_13,
            "(=.,=)" to R.drawable.normal_14,
            "(:P)" to R.drawable.normal_15,
            "(:P)" to R.drawable.normal_16,
        )
    }

    val tvEmoji by lazy {
        linkedMapOf(
            "(bgm24)" to R.drawable.tv_01,
            "(bgm25)" to R.drawable.tv_02,
            "(bgm26)" to R.drawable.tv_03,
            "(bgm27)" to R.drawable.tv_04,
            "(bgm28)" to R.drawable.tv_05,
            "(bgm29)" to R.drawable.tv_06,
            "(bgm30)" to R.drawable.tv_07,
            "(bgm31)" to R.drawable.tv_08,
            "(bgm32)" to R.drawable.tv_09,
            "(bgm33)" to R.drawable.tv_10,
            "(bgm34)" to R.drawable.tv_11,
            "(bgm35)" to R.drawable.tv_12,
            "(bgm36)" to R.drawable.tv_13,
            "(bgm37)" to R.drawable.tv_14,
            "(bgm38)" to R.drawable.tv_15,
            "(bgm39)" to R.drawable.tv_16,
            "(bgm40)" to R.drawable.tv_17,
            "(bgm41)" to R.drawable.tv_18,
            "(bgm42)" to R.drawable.tv_19,
            "(bgm43)" to R.drawable.tv_20,
            "(bgm44)" to R.drawable.tv_21,
            "(bgm45)" to R.drawable.tv_22,
            "(bgm46)" to R.drawable.tv_23,
            "(bgm47)" to R.drawable.tv_24,
            "(bgm48)" to R.drawable.tv_25,
            "(bgm49)" to R.drawable.tv_26,
            "(bgm50)" to R.drawable.tv_27,
            "(bgm51)" to R.drawable.tv_28,
            "(bgm52)" to R.drawable.tv_29,
            "(bgm53)" to R.drawable.tv_30,
            "(bgm54)" to R.drawable.tv_31,
            "(bgm55)" to R.drawable.tv_32,
            "(bgm56)" to R.drawable.tv_33,
            "(bgm57)" to R.drawable.tv_34,
            "(bgm58)" to R.drawable.tv_35,
            "(bgm59)" to R.drawable.tv_36,
            "(bgm60)" to R.drawable.tv_37,
            "(bgm61)" to R.drawable.tv_38,
            "(bgm62)" to R.drawable.tv_39,
            "(bgm63)" to R.drawable.tv_40,
            "(bgm64)" to R.drawable.tv_41,
            "(bgm65)" to R.drawable.tv_42,
            "(bgm66)" to R.drawable.tv_43,
            "(bgm67)" to R.drawable.tv_44,
            "(bgm68)" to R.drawable.tv_45,
            "(bgm69)" to R.drawable.tv_46,
            "(bgm70)" to R.drawable.tv_47,
            "(bgm71)" to R.drawable.tv_48,
            "(bgm72)" to R.drawable.tv_49,
            "(bgm73)" to R.drawable.tv_50,
            "(bgm74)" to R.drawable.tv_51,
            "(bgm75)" to R.drawable.tv_52,
            "(bgm76)" to R.drawable.tv_53,
            "(bgm77)" to R.drawable.tv_54,
            "(bgm78)" to R.drawable.tv_55,
            "(bgm79)" to R.drawable.tv_56,
            "(bgm80)" to R.drawable.tv_57,
            "(bgm81)" to R.drawable.tv_58,
            "(bgm82)" to R.drawable.tv_59,
            "(bgm83)" to R.drawable.tv_60,
            "(bgm84)" to R.drawable.tv_61,
            "(bgm85)" to R.drawable.tv_62,
            "(bgm86)" to R.drawable.tv_63,
            "(bgm87)" to R.drawable.tv_64,
            "(bgm88)" to R.drawable.tv_65,
            "(bgm89)" to R.drawable.tv_66,
            "(bgm90)" to R.drawable.tv_67,
            "(bgm91)" to R.drawable.tv_68,
            "(bgm92)" to R.drawable.tv_69,
            "(bgm93)" to R.drawable.tv_70,
            "(bgm94)" to R.drawable.tv_71,
            "(bgm95)" to R.drawable.tv_72,
            "(bgm96)" to R.drawable.tv_73,
            "(bgm97)" to R.drawable.tv_74,
            "(bgm98)" to R.drawable.tv_75,
            "(bgm99)" to R.drawable.tv_76,
            "(bgm100)" to R.drawable.tv_77,
            "(bgm101)" to R.drawable.tv_78,
            "(bgm102)" to R.drawable.tv_79,
            "(bgm103)" to R.drawable.tv_80,
            "(bgm104)" to R.drawable.tv_81,
            "(bgm105)" to R.drawable.tv_82,
            "(bgm106)" to R.drawable.tv_83,
            "(bgm107)" to R.drawable.tv_84,
            "(bgm108)" to R.drawable.tv_85,
            "(bgm109)" to R.drawable.tv_86,
            "(bgm110)" to R.drawable.tv_87,
            "(bgm111)" to R.drawable.tv_88,
            "(bgm112)" to R.drawable.tv_89,
            "(bgm113)" to R.drawable.tv_90,
            "(bgm114)" to R.drawable.tv_91,
            "(bgm115)" to R.drawable.tv_92,
            "(bgm116)" to R.drawable.tv_93,
            "(bgm117)" to R.drawable.tv_94,
            "(bgm118)" to R.drawable.tv_95,
            "(bgm119)" to R.drawable.tv_96,
            "(bgm120)" to R.drawable.tv_97,
            "(bgm121)" to R.drawable.tv_98,
            "(bgm122)" to R.drawable.tv_99,
            "(bgm123)" to R.drawable.tv_100,
            "(bgm124)" to R.drawable.tv_101,
            "(bgm125)" to R.drawable.tv_102
        )
    }

    val bgmEmoji by lazy {
        linkedMapOf(
            "(bgm01)" to R.drawable.bgm_01,
            "(bgm02)" to R.drawable.bgm_02,
            "(bgm03)" to R.drawable.bgm_03,
            "(bgm04)" to R.drawable.bgm_04,
            "(bgm05)" to R.drawable.bgm_05,
            "(bgm06)" to R.drawable.bgm_06,
            "(bgm07)" to R.drawable.bgm_07,
            "(bgm08)" to R.drawable.bgm_08,
            "(bgm09)" to R.drawable.bgm_09,
            "(bgm10)" to R.drawable.bgm_10,
            "(bgm11)" to R.drawable.bgm_11,
            "(bgm12)" to R.drawable.bgm_12,
            "(bgm13)" to R.drawable.bgm_13,
            "(bgm14)" to R.drawable.bgm_14,
            "(bgm15)" to R.drawable.bgm_15,
            "(bgm16)" to R.drawable.bgm_16,
            "(bgm17)" to R.drawable.bgm_17,
            "(bgm18)" to R.drawable.bgm_18,
            "(bgm19)" to R.drawable.bgm_19,
            "(bgm20)" to R.drawable.bgm_20,
            "(bgm21)" to R.drawable.bgm_21,
            "(bgm22)" to R.drawable.bgm_22,
            "(bgm23)" to R.drawable.bgm_23
        )
    }
}