GET https://search.douban.com/movie/subject_search?search_text=芙莉莲

###
GET https://frodo.douban.com/api/v2/elessar/subject/27260217/photos?apikey=0dad551ec0f84ed02907ff5c42e8ec70&count=10&
    start=1&_sig=a8Ehox%2B3n7af0aV9M3iJn3aIMyc%3D&_ts=1702273629
User-Agent: api-client/1 com.douban.frodo/6.42.2(194) Android/22 product/shamu vendor/OPPO model/OPPO R11 Plus  rom/android  network/wifi  platform/mobile nd/1

###
GET https://frodo.douban.com/api/v2/search/subjects?q=鲁路修&count=20&apikey=0dad551ec0f84ed02907ff5c42e8ec70&
    _sig=HI1RXXo7Sfy6GJUmrFWpLf47C%2Fw%3D&_ts=1702278419
User-Agent: api-client/1 com.douban.frodo/7.65.0(277) Android/33 product/coral vendor/Google model/Pixel 4 XL brand/google  rom/android  network/wifi  udid/0643fa6abfd3eaff076ff3ee603211ded11fc344  platform/mobile nd/1
Host: frodo.douban.com
Connection: Keep-Alive
Accept-Encoding: gzip

###
GET  https://frodo.douban.com/api/v2/search/subjects?q=%E6%B4%9B%E5%9F%BA%20%E7%AC%AC%E4%BA%8C%E5%AD%A3&count=10&
    apikey=0dad551ec0f84ed02907ff5c42e8ec70&_sig=9UFC7QxDqpMRZEZbOYztloRtEvY%3D&_ts=1702293719
User-Agent: api-client/1 com.douban.frodo/7.65.0(277) Android/33 product/coral vendor/Google model/Pixel 4 XL brand/google  rom/android  network/wifi  udid/0643fa6abfd3eaff076ff3ee603211ded11fc344  platform/mobile nd/1
Host: frodo.douban.com
Connection: Keep-Alive
Accept-Encoding: gzip

###
GET /api/v2/search/suggestion?q=%E8%8A%99%E8%8E%89%E8%8E%B2&loc_id=108288&apikey=0dad551ec0f84ed02907ff5c42e8ec70&
    channel=Yingyongbao_Market&udid=0643fa6abfd3eaff076ff3ee603211ded11fc344&os_rom=android&timezone=Asia%2FShanghai&
    _sig=D10PrhXPSwQb30bWnPb9NwSS5yc%3D&_ts=1702294026 HTTP/1.1
User-Agent: api-client/1 com.douban.frodo/7.65.0(277) Android/33 product/coral vendor/Google model/Pixel 4 XL brand/google  rom/android  network/wifi  udid/0643fa6abfd3eaff076ff3ee603211ded11fc344  platform/mobile nd/1
Host: frodo.douban.com
Connection: Keep-Alive
Accept-Encoding: gzip


###
GET /api/v2/search/subjects?q=%E8%91%AC%E9%80%81%E7%9A%84%E8%8A%99%E8%8E%89%E8%8E%B2&count=20&loc_id=108288&
    apikey=0dad551ec0f84ed02907ff5c42e8ec70&channel=Yingyongbao_Market&udid=0643fa6abfd3eaff076ff3ee603211ded11fc344&
    os_rom=android&timezone=Asia%2FShanghai&_sig=HI1RXXo7Sfy6GJUmrFWpLf47C%2Fw%3D&_ts=1702278419
User-Agent: api-client/1 com.douban.frodo/7.65.0(277) Android/33 product/coral vendor/Google model/Pixel 4 XL brand/google  rom/android  network/wifi  udid/0643fa6abfd3eaff076ff3ee603211ded11fc344  platform/mobile nd/1
Host: frodo.douban.com
Connection: Keep-Alive
Accept-Encoding: gzip

###
GET /group/topic/8465 HTTP/2
Host: bgm.tv
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:120.0) Gecko/20100101 Firefox/120.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.6,zh-HK;q=0.4,en;q=0.2
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Cookie: chii_sec_id=kdF%2FABxP80aJb6z9a8ELlL40nCqgK2Kpi0Uq4A; _ga_1109JLGMHN=GS1.1.1702403786.23.1.1702403897.0.0.0; chii_theme=light; _ga=GA1.1.1847849586.1702102284; __utma=1.1847849586.1702102284.1702399295.1702403792.23; __utmz=1.1702102284.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); chii_cookietime=0; __utmc=1; chii_sid=G8ya0S; chii_auth=lYx7BRhF8hufaPz3a8ABx8JBgE3WDFWYrREugSXlQVUIIqmbuNTvJboY9UqBUjSqTC7i5L4sBaZiSTA9ttzr70k4cPhkRqRWCSbE; __utmb=1.7.10.1702403792; __utmt=1
Upgrade-Insecure-Requests: 1
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: same-origin
Sec-Fetch-User: ?1
Pragma: no-cache
Cache-Control: no-cache
TE: trailers


###
GET https://tinygrail.oss-cn-hangzhou.aliyuncs.com/avatar/edbbcd8f731821b6172a74bf1e6ba9ec.jpg
Referer: https://bgm.tv


###
GET https://frodo.douban.com/api/v2/search/suggestion?q=%E6%B5%B7%E8%B4%BC%E7%8E%8B&
    apikey=0dad551ec0f84ed02907ff5c42e8ec70&_sig=YIaBWngsMazLHzYtVn50BAbHTkc%3D&_ts=1703084439&count=10
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: cross-site
Pragma: no-cache
Cache-Control: no-cache
TE: trailers
Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.6,zh-HK;q=0.4,en;q=0.2
Referer: https://frodo.douban.com/api/v2/search/suggestion?q=%E6%B5%B7%E8%B4%BC%E7%8E%8B&apikey=0dad551ec0f84ed02907ff5c42e8ec70
User-Agent: api-client/1 com.douban.frodo/7.65.0(277) Android/33 product/coral vendor/Google model/Pixel 4 XL brand/google  rom/android  network/wifi  udid/0643fa6abfd3eaff076ff3ee603211ded11fc344  platform/mobile nd/1
Host: frodo.douban.com
Connection: Keep-Alive
Accept-Encoding: gzip

###
GET https://next.bgm.tv/demo/
Host: bangumi.tv
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:120.0) Gecko/20100101 Firefox/120.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.6,zh-HK;q=0.4,en;q=0.2
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Referer: https://bangumi.tv/user/837364
Cookie: chii_sec_id=wtovCh4RoRqPb7PrdMAXlqExgySQG16Y%2BRES; chii_theme=light; __utma=1.1297479166.1702737965.1703344620.1703391051.18; __utmz=1.1702737965.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); _ga_1109JLGMHN=GS1.1.1703391043.18.1.1703391525.0.0.0; _ga=GA1.1.856405988.1702737965; chii_cookietime=0; __utmc=1; chii_searchDateLine=0; prg_list_mode=full; prg_display_mode=normal; __utmb=1.18.10.1703391051; __utmt=1; chii_sid=00ZZik; chii_auth=lYx7BRhF8hufaPz3a8ABx8JBgE3WDFWYrREugSXlQVUIIqmbuNTvJboY9UqBUjSqTC7i5L4sBaZiSTA9ttzr70k4cPhkRqRWCSbE
Upgrade-Insecure-Requests: 1
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: same-origin
Sec-Fetch-User: ?1
Pragma: no-cache
Cache-Control: no-cache


###
# @no-redirect
POST https://bangumi.tv/oauth/authorize?response_type=code&redirect_uri=http://localhost/callback&
    client_id=bgm285565606da641d78
Host: bgm.tv
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:120.0) Gecko/20100101 Firefox/120.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.6,zh-HK;q=0.4,en;q=0.2
Accept-Encoding: gzip, deflate, br
Content-Type: application/x-www-form-urlencoded
Origin: https://bgm.tv
Connection: keep-alive
Cookie: chii_sec_id=ldBwUU5O8UaJb6z9a8ELlL40nCqgKy%2F0mmMD6g; _ga_1109JLGMHN=GS1.1.1703391951.34.1.1703392218.0.0.0; chii_theme=light; _ga=GA1.1.850200014.1702704411; __utma=1.850200014.1702704411.1703171716.1703391951.30; __utmz=1.1702704413.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); chii_cookietime=2592000; __utmc=1; chii_searchDateLine=0; chii_sid=KbL0uw; prg_display_mode=normal; __utmb=1.6.10.1703391951; __utmt=1; chii_auth=lYx7BRhF8hufaPz3a8ABx8JBgE3WDFWYrREugSXlQVUIIqmbuNTvJboY9UqBUjSqTC7i5L4sBaZiSTA9ttzr70k4cPhkRqRWCSbE
Pragma: no-cache
Cache-Control: no-cache
TE: trailers

formhash = 275b091c &
submit = %E6%8E%88%E6%9D%83 &
client_id = bgm285565606da641d78

###
POST https://bgm.tv/oauth/access_token
Content-Type: application/x-www-form-urlencoded

###
POST https://bgm.tv/oauth/token_status
Content-Type: application/x-www-form-urlencoded

access_token = 0df589bbce14321dd835f6b8fe343b49a5052ad2

###
# @no-redirect
POST https://bangumi.tv/oauth/authorize?response_type=code&redirect_uri=http://localhost/callback&
    client_id=bgm285565606da641d78
Host: bgm.tv
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:120.0) Gecko/20100101 Firefox/120.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.6,zh-HK;q=0.4,en;q=0.2
Accept-Encoding: gzip, deflate, br
Content-Type: application/x-www-form-urlencoded
Origin: https://bgm.tv
Connection: keep-alive
Cookie: chii_sec_id=ldBwUU5O8UaJb6z9a8ELlL40nCqgKy%2F0mmMD6g; _ga_1109JLGMHN=GS1.1.1703391951.34.1.1703392218.0.0.0; chii_theme=light; _ga=GA1.1.850200014.1702704411; __utma=1.850200014.1702704411.1703171716.1703391951.30; __utmz=1.1702704413.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); chii_cookietime=2592000; __utmc=1; chii_searchDateLine=0; chii_sid=KbL0uw; prg_display_mode=normal; __utmb=1.6.10.1703391951; __utmt=1; chii_auth=lYx7BRhF8hufaPz3a8ABx8JBgE3WDFWYrREugSXlQVUIIqmbuNTvJboY9UqBUjSqTC7i5L4sBaZiSTA9ttzr70k4cPhkRqRWCSbE
Pragma: no-cache
Cache-Control: no-cache
TE: trailers



###
# @no-redirect
GET https://bgm.tv/group/topic/391984


###
GET https://api.github.com/repos/xiaoyvyv/Bangumi-Data/contents/data/collection.json
Accept: application/vnd.github+json
Authorization: Bearer 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
X-GitHub-Api-Version: 2022-11-28


###
PUT https://api.github.com/repos/xiaoyvyv/Bangumi-Data/contents/data/collection.json
Accept: application/vnd.github+json
Authorization: Bearer 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
X-GitHub-Api-Version: 2022-11-28
Content-Type: application/json

{
  "message": "更新收藏",
  "committer": {
    "name": "Monalisa Octocat",
    "email": "octocat@github.com"
  },
  "content": "5pu05paw5pS26JeP5pu05paw5pS26JeP",
  "sha": "5b631fb1cd75c9c67ef891b7e3bb4ddb13391eca"
}

###
GET https://api.github.com/repos/xiaoyvyv/Bangumi-Data/contents/data/Application.musicdb
Accept: application/vnd.github+json
Authorization: Bearer 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
X-GitHub-Api-Version: 2022-11-28

###



