package com.xiaoyv.bangumi.shared.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF445E91)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFD8E2FF)
val onPrimaryContainerLight = Color(0xFF2B4678)
val secondaryLight = Color(0xFF575E71)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFDBE2F9)
val onSecondaryContainerLight = Color(0xFF3F4759)
val tertiaryLight = Color(0xFF715573)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFBD7FC)
val onTertiaryContainerLight = Color(0xFF583E5B)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFF9F9FF)
val onBackgroundLight = Color(0xFF1A1B20)
val surfaceLight = Color(0xFFF9F9FF)
val onSurfaceLight = Color(0xFF1A1B20)
val surfaceVariantLight = Color(0xFFE1E2EC)
val onSurfaceVariantLight = Color(0xFF44474F)
val outlineLight = Color(0xFFE0E0E0)
val outlineVariantLight = Color(0xFFEEEEEE)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2F3036)
val inverseOnSurfaceLight = Color(0xFFF0F0F7)
val inversePrimaryLight = Color(0xFFADC6FF)
val surfaceDimLight = Color(0xFFD9D9E0)
val surfaceBrightLight = Color(0xFFF9F9FF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF3F3FA)
val surfaceContainerLight = Color(0xFFEDEDF4)
val surfaceContainerHighLight = Color(0xFFE8E7EE)
val surfaceContainerHighestLight = Color(0xFFE2E2E9)


val primaryDark = Color(0xFFADC6FF)
val onPrimaryDark = Color(0xFF102F60)
val primaryContainerDark = Color(0xFF2B4678)
val onPrimaryContainerDark = Color(0xFFD8E2FF)
val secondaryDark = Color(0xFFBFC6DC)
val onSecondaryDark = Color(0xFF293041)
val secondaryContainerDark = Color(0xFF3F4759)
val onSecondaryContainerDark = Color(0xFFDBE2F9)
val tertiaryDark = Color(0xFFDEBCDF)
val onTertiaryDark = Color(0xFF402843)
val tertiaryContainerDark = Color(0xFF583E5B)
val onTertiaryContainerDark = Color(0xFFFBD7FC)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF111318)
val onBackgroundDark = Color(0xFFE2E2E9)
val surfaceDark = Color(0xFF111318)
val onSurfaceDark = Color(0xFFE2E2E9)
val surfaceVariantDark = Color(0xFF44474F)
val onSurfaceVariantDark = Color(0xFFC4C6D0)
val outlineDark = Color(0xFF8E9099)
val outlineVariantDark = Color(0xFF44474F)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE2E2E9)
val inverseOnSurfaceDark = Color(0xFF2F3036)
val inversePrimaryDark = Color(0xFF445E91)
val surfaceDimDark = Color(0xFF111318)
val surfaceBrightDark = Color(0xFF37393E)
val surfaceContainerLowestDark = Color(0xFF0C0E13)
val surfaceContainerLowDark = Color(0xFF1A1B20)
val surfaceContainerDark = Color(0xFF1E1F25)
val surfaceContainerHighDark = Color(0xFF282A2F)
val surfaceContainerHighestDark = Color(0xFF33353A)


/**
 * Custom
 */
val colorCollectionWishContainer = Color(0xFFF09199)
val colorCollectionWishText = Color.White
val colorCollectionDoingContainer = Color(0xFF36CA36)
val colorCollectionDoneContainer = Color(0xFF4897FF)
val colorCollectionDoneContainerAlpha = Color(0x9F4897FF)
val colorCollectionDoneText = Color.White
val colorCollectionDoingText = Color.White
val colorCollectionOnHoldContainer = Color(0xFFFF9800)
val colorCollectionOnHoldText = Color.White
val colorCollectionDroppedContainer = Color(0xFFF44336)
val colorCollectionDroppedText = Color.White
val colorStateAiringContainer = Color(0xFF4CAF50)
val colorStateAiringText = Color.White
val colorStateAiredContainer = Color(0xFFDAEAFF)
val colorStateAiredText = Color(0xFF0066CC)
val colorChartC1 = Color(0xFF67B7DC)
val colorChartC2 = Color(0xFF6794DC)
val colorChartC3 = Color(0xFF6771DC)
val colorChartC4 = Color(0xFF8067DC)
val colorChartC5 = Color(0xFFA267DC)
val colorChartC6 = Color(0xFFC767DC)
val colorChartC7 = Color(0xFFDC67CE)
val colorRankBar1 = Color(0xFF4CAF50)
val colorRankBar1Alpha = Color(0x3F4CAF50)
val colorRankBar2 = Color(0xFF999999)
val colorRankBar2Alpha = Color(0x3F999999)
val colorChartStatisticsCollect = Color(0xFFF09199)
val colorChartStatisticsFinish = Color(0xFF70B941)
val colorChartStatisticsFinishRate = Color(0xFF6BAAE8)
val colorChartStatisticsAverage = Color(0xFFE68E46)
val colorChartStatisticsStander = Color(0xFF9065ED)
val colorChartStatisticsComments = Color(0xFF369CF8)
val colorQuestionRight = Color(0xFF55CC55)
val colorQuestionError = Color(0xFFCC5555)
val colorFileVideo = Color(0xFF6161F3)
val colorFileAudio = Color(0xFF009688)
val colorFileImage = Color(0xFFFB766C)
val colorFileCode = Color(0xFF2196F3)
val colorFileOffice = Color(0xFFE64A7F)
val colorFileZip = Color(0xFFEDBB24)
val colorFileInstall = Color(0xFF9C27B0)
val colorFileTxt = Color(0xFF673AB7)

