name: Compose Multiplatform CI

on:
  push:
    branches: [ 'multiplatform' ]
  pull_request:
    branches: [ 'multiplatform' ]

jobs:
  build:
    runs-on: macos-latest
    env:
      JAVA_HOME: /Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      # 安装 Cocoapods
      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          pod repo update

      # 安装 Java
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: gradle

      # 安装 Android SDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      #      # 构建 Android APK
      #      - name: Build Android Release
      #        id: build
      #        continue-on-error: true
      #        run: ./gradlew :composeApp:assembleRelease --info
      #
      #      # 上传 Android APK
      #      - name: Upload Android APK
      #        uses: actions/upload-artifact@v4
      #        with:
      #          name: android-release-apk
      #          path: composeApp/build/outputs/apk/release/*.apk

      - name: generateDummyFramework
        run: ./gradlew generateDummyFramework --info

      - name: podspec
        run: ./gradlew podspec --info

      # Embed
      - name: Embed and sign framework for iOS
        run: ./gradlew :composeApp:embedAndSignAppleFrameworkForXcode --info

      # 构建 iOS
      - name: Build iOS Release
        run: |
          cd iosApp
          pod install
          xcodebuild \
            -scheme iosApp \
            -configuration Release \
            -workspace iosApp.xcworkspace \
            -sdk iphoneos \
            -archivePath build/iosApp.xcarchive archive
            ENABLE_USER_SCRIPT_SANDBOXING=NO

      # 导出 IPA
      - name: Export iOS IPA
        run: |
          xcodebuild -exportArchive \
            -archivePath iosApp/build/iosApp.xcarchive \
            -exportPath iosApp/build/ipa \
            -exportOptionsPlist iosApp/ExportOptions.plist

      # 上传 IPA
      - name: Upload iOS IPA
        uses: actions/upload-artifact@v4
        with:
          name: ios-release-ipa
          path: iosApp/build/ipa/*.ipa
